add_newline = false
command_timeout = 200

[character]
error_symbol = "[✗](bold cyan)"
success_symbol = "[❯](bold cyan)"

[directory]
truncation_length = 2
truncation_symbol = "…/"
repo_root_style = "bold cyan"
repo_root_format = "[$repo_root]($repo_root_style)[$path]($style)[$read_only]($read_only_style) "

[git_status]
format = '([$all_status$ahead_behind]($style) )'
style = "cyan"

ahead = "[⇡${count} ](green)"
behind = "[⇣${count} ](red)"
diverged = "[⇕](cyan)[⇡${ahead_count}](208)[⇣${behind_count}](red) "
up_to_date = "[ ](green)"

conflicted = "[ ](red)"
untracked = ""
modified = "[! ](red)"
staged = ""
stashed = ""
renamed = ""
deleted = ""
